version: 2
jobs:
  build-deploy:
    working_directory: ~/tmp
    docker:
    - image: circleci/python:2.7-jessie
    steps:
    - run: sudo pip install awscli
    - run: sudo apt-get update
    - run: sudo apt-get install nodejs
    - run: sudo apt-get install npm
    - checkout
    - run: npm install
    - run: npm run build
    - deploy:
        name: Deploy to S3 if branch is Master
        command: aws s3 sync build s3://demo.woosmap.com/baidu/ --region eu-central-1 --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
    - build-deploy:
        filters:
          branches:
            only: master